version: "3"
services:
#  redis:
#    image: redis:alpine
#    ports:
#      - "6379"
  crossbar_1:
    build: docker/crossbar
    ports:
      - "8001:8000"
    volumes:
      - ./lesson-1:/app
    environment:
      - TZ=Europe/London
  http:
    image: httpd:2.4
    ports:
      - "8081:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs/
    environment:
      - TZ=Europe/London
  crossbar_2:
    build: docker/crossbar
    ports:
      - "8002:8000"
    volumes:
      - ./lesson-2:/app
    environment:
      - TZ=Europe/London
  crossbar_3:
    build: docker/crossbar
    ports:
      - "8003:8000"
    volumes:
      - ./lesson-3/.crossbar:/app/.crossbar
      - ./lesson-3/logs:/app/logs
      - ./vendor/:/app/vendor
    environment:
      - TZ=Europe/London

