version: "3"
services:
#  redis:
#    image: redis:alpine
#    ports:
#      - "6379"
  crossbar_1:
    build: docker/crossbar
    ports:
      - "8001:8000"
    volumes:
      - ./lesson-1:/app
    environment:
      - TZ=Europe/London
  http:
    image: httpd:2.4
    ports:
      - "8081:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs/
    environment:
      - TZ=Europe/London
  crossbar_2:
    build: docker/crossbar
    ports:
      - "8002:8000"
    volumes:
      - ./lesson-2:/app
    environment:
      - TZ=Europe/London
  crossbar_3:
    build: docker/crossbar
    ports:
      - "8003:8000"
    volumes:
      - ./lesson-3/router:/app
    environment:
      - TZ=Europe/London
  crossbar_4:
    build: docker/crossbar-php
    ports:
      - "8004:8000"
    volumes:
      - ./lesson-4/router:/app
    environment:
      - TZ=Europe/London
  php_3:
    build: docker/php
    volumes:
      - ./lesson-3/php:/app
    network_mode: "host"
    environment:
      - TZ=Europe/London
    command: php /app/client.php
  php_4:
    build: docker/php
    volumes:
      - ./lesson-4/php:/app
    network_mode: "host"
    environment:
      - TZ=Europe/London
    command: php /app/client.php


