version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  redis_ui:
    image: marian/rebrow
    ports:
      - "5001:5001"
  crossbar_1:
    build: docker/crossbar
    image: phpyorkshire/crossbar
    ports:
      - "8001:8000"
    volumes:
      - ./lesson-1/router:/app
    environment:
      - TZ=Europe/London
  crossbar_2:
    build: docker/crossbar
    image: phpyorkshire/crossbar
    ports:
      - "8002:8000"
    volumes:
      - ./lesson-2/router:/app
    environment:
      - TZ=Europe/London
  crossbar_3:
    build: docker/crossbar
    image: phpyorkshire/crossbar
    ports:
      - "8003:8000"
    volumes:
      - ./lesson-3/router:/app
    environment:
      - TZ=Europe/London
  crossbar_4:
    build: docker/crossbar-php
    image: phpyorkshire/crossbar-php
    ports:
      - "8004:8000"
    volumes:
      - ./lesson-4/router:/app
    environment:
      - TZ=Europe/London
  crossbar_5:
    build: docker/crossbar-php
    image: phpyorkshire/crossbar-php
    ports:
      - "8005:8000"
    volumes:
      - ./lesson-5/router:/app
    environment:
      - TZ=Europe/London
  crossbar_6:
    build: docker/crossbar-php
    image: phpyorkshire/crossbar-php
    ports:
      - "8006:8000"
    volumes:
      - ./lesson-6/router:/app
  crossbar_6a:
    build: docker/crossbar-php
    image: phpyorkshire/crossbar-php
    ports:
      - "8007:8000"
    volumes:
      - ./lesson-6a/router:/app
    env_file:
      - ./docker/zmq.env
  http:
    image: httpd:2.4
    ports:
      - "8081:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs/
  php_3:
    build: docker/php-client
    image: phpyorkshire/php
    volumes:
      - ./lesson-3/php:/app
    network_mode: "host"
    command: php /app/client.php
  app_4:
    build: docker/php-app
    image: phpyorkshire/php-app
    ports:
      - "8014:80"
    volumes:
      - ./lesson-4/php:/app
      - ./db:/db
    command: php -S 0.0.0.0:80 -t /app/
  app_5:
    build: docker/php-app
    image: phpyorkshire/php-app
    ports:
      - "8015:80"
    volumes:
      - ./lesson-5/php:/app
      - ./db:/db
    command: php -S 0.0.0.0:80 -t /app/
  zmq_6:
    build: docker/php-zmq
    image: phpyorkshire/php-zmq
    volumes:
      - ./lesson-6a/php:/app
      - ./db:/db
    environment:
      - TZ=Europe/London
    env_file:
      - ./docker/zmq.env
    command: php /app/zmq.php


